---
- name: Fetch Incident and Update Incident fields data from ServiceNow
  hosts: localhost
  gather_facts: no
  vars:
    short_Descriptions: "{{ short_Descriptions }}"
    mysql_query: "SELECT * FROM incidentdata.incidentConfigDetails;;"
    file_path: "inputValidationUsecasePayload.txt"
    impacted_ci_List: []
  tasks:
    - block:
        - name: Read data from payload file
          slurp:
            src: "{{ file_path }}"
          register: file_content

        - name: Convert file content to JSON
          set_fact:
            json_data: "{{ file_content.content | b64decode | from_json }}"

        - name: Display the file data
          debug:
            var: json_data

        - name: Extract Impacted CI values and append to the list
          set_fact:
            impacted_ci_List: "{{ impacted_ci_List + [item] }}"
          loop: "{{ json_data.body | json_query('[*].impactedCi') }}"

        - name: Display the impacted ci list
          debug:
            var: impacted_ci_List

        - name: Include MySQL Query Playbook for Each Impacted CI
          include_tasks: mysql_query_playbook.yml
          with_items: "{{ impacted_ci_List }}"
          loop_control:
            loop_var: impacted_ci
          vars:  
            login_host: "{{ var_db_hostname }}"
            login_user: "{{ var_db_username }}"
            login_password: "{{ var_db_password }}"
            #login_db: "incidentdata"
            login_port: "{{ var_db_port }}"
            query: "SELECT * FROM incidentdata.ci_details where ci_name = '{{ impacted_ci }}' ;"
          - name: Print SQL Query
            debug:
              var: query


    - name: Display Return Output from MySQL Query Playbook
      debug:
        var: impacted_ci_details
      when: impacted_ci_details is defined  # Display only if the variable is defined
