---
- name: Fetch Incident and Update Incident fields data from ServiceNow
  hosts: localhost
  gather_facts: no
  vars:
    short_Descriptions: "{{ short_Descriptions }}"
    mysql_query: "SELECT * FROM incidentdata.incidentConfigDetails;;"
    file_path: "inputValidationUsecasePayload.txt"
    impacted_ci_List: []

  tasks:
    - block:
        - name: Read data from payload file
          slurp:
            src: "{{ file_path }}"
          register: file_content

        - name: Convert file content to JSON
          set_fact:
            json_data: "{{ file_content.content | b64decode | from_json }}"

        - name: Display the file data
          debug:
            var: json_data

        - name: Extract Impacted CI values and append to the list
          set_fact:
            impacted_ci_List: "{{ impacted_ci_List + [item] }}"
          loop: "{{ json_data.body | json_query('[*].impactedCi') }}"

        - name: Display the impacted ci list
          debug:
            var: impacted_ci_List

        - name: Include MySQL Query Playbook for Each Impacted CI
          include_tasks: mysql_query_playbook.yml
          with_items: "{{ impacted_ci_List }}"
          loop_control:
            loop_var: impacted_ci
          vars:  
            query: "SELECT * FROM incidentdata.ci_details where ci_name = '{{ impacted_ci }}' ;"

            # Add a task to fetch cred details from creddetails table for each impacted CI
            - name: Fetch Cred Details for Impacted CI
              mysql_query:
                query: "SELECT credId FROM incredId-details where os = '{{ query_result.os }}' and restrict = '{{ query_result.install_status}}' and non-restrict = '{{ query_result.operational_status }}' and prod-EU-Domain = '{{ query_result.dns_domain}}';"
              register: cred_details_result

            # Display the cred details result
            - name: Display Cred Details Result
              debug:
                var: cred_details_result
