---
- name: Fetch Incident and Update Incident fields data from ServiceNow
  hosts: localhost
  gather_facts: no
  vars:
    short_Descriptions: "{{ short_Descriptions }}"
    mysql_query: "SELECT * FROM incidentdata.incidentConfigDetails;;"
    file_path: "inputValidationUsecasePayload.txt"
    impacted_ci_List: []

  tasks:
    - block:
        - name: Read data from payload file
          slurp:
            src: "{{ file_path }}"
          register: file_content

        - name: Convert file content to JSON
          set_fact:
            json_data: "{{ file_content.content | b64decode | from_json }}"

        - name: Display the file data
          debug:
            var: json_data

        - name: Extract Impacted CI values and append to the list
          set_fact:
            impacted_ci_List: "{{ impacted_ci_List + [item] }}"
          loop: "{{ json_data.body | json_query('[*].impactedCi') }}"

        - name: Display the impacted ci list
          debug:
            var: impacted_ci_List

        - name: Include MySQL Query Playbook for Each Impacted CI
          include_tasks: mysql_query_playbook.yml
          with_items: "{{ impacted_ci_List }}"
          loop_control:
            loop_var: impacted_ci
          vars:  
            query: "SELECT * FROM incidentdata.ci_details where ci_name = '{{ impacted_ci }}' ;"
            #query: "SELECT credId FROM incredId-details where os = '{{ query_result.query_result[0][0].os }}' and restrict = '{{ query_result.query_result[0][0].install_status}}' and non-restrict = '{{ query_result.query_result[0][0].operational_status }}' and prod-EU-Domain = '{{ query_result.query_result[0][0].dns_domain}}';"
            second_query_template: |
              SELECT credId FROM incredId-details
              WHERE os = '{{ query_result.results[0].rows[0].os }}'
              AND restrict = '{{ query_result.results[0].rows[0].install_status}}'
              AND non-restrict = '{{ query_result.results[0].rows[0].operational_status }}'
              AND prod-EU-Domain = '{{ query_result.results[0].rows[0].dns_domain}}';"
        - name: Fetch Cred Details for Impacted CI
          include_tasks: mysql_query_playbook.yml
          vars: 
            query: "SELECT credId FROM incredId-details where os = '{{ query_result.query_result[0][0].os }}' and restrict = '{{ query_result.query_result[0][0].install_status}}' and non-restrict = '{{ query_result.query_result[0][0].operational_status }}' and prod-EU-Domain = '{{ query_result.query_result[0][0].dns_domain}}';"
          register: cred_details_result

        - name: Display Cred Details Result
          debug:
            var: cred_details_result
