---
- name: Fetch Incident and Update Incident fields data from ServiceNow
  hosts: localhost
  gather_facts: no
  vars:
    short_Descriptions: "{{ short_Descriptions }}"
    mysql_query: "SELECT * FROM incidentdata.incidentConfigDetails;;"
    file_path: "inputValidationUsecasePayload.txt"
    impacted_ci_List: []
    ticketType: "e2e"

  tasks:
    - name: Read data from payload file
      slurp:
        src: "{{ file_path }}"
      register: file_content

    - name: Convert file content to JSON
      set_fact:
        json_data: "{{ file_content.content | b64decode | from_json }}"

    - name: Display the file data
      debug:
        var: json_data

    - name: Extract Impacted CI values and append to the list
      set_fact:
        impacted_ci_List: "{{ impacted_ci_List + [item] }}"
      loop: "{{ json_data.body | json_query('[*].impactedCi') }}"

    - name: Display the impacted ci list
      debug:
        var: impacted_ci_List

    - name: Loop through impacted CIs and include tasks
      include_tasks: mysql_query_playbook.yml
      loop: "{{ impacted_ci_List }}"
      loop_control:
        loop_var: impacted_ci
      vars:  
        #query: "SELECT * FROM incidentdata.ci_details where ci_name = '{{ impacted_ci }}' ;"
        query: "SELECT ci_name, credId FROM incidentdata.ci_details ci INNER JOIN incidentdata.`credId-details` cr ON ci.os = cr.os and ci.dns_domain = cr.`prod-EU-Domain` and ci.credType = cr.credType  where ci_name = '{{ impacted_ci }}';"
        #query2: "SELECT credId FROM incredId-details where os = '{{ query_result_item.item.0.os }}' and restrict = '{{ query_result_item.item.0.install_status }}' and non-restrict = '{{ query_result_item.item.0.operational_status }}' and prod-EU-Domain = '{{ query_result_item.item.0.dns_domain }}';"
      #register: query_result

    - name: Loop through impacted CIs and include tasks
      include_tasks: mysql_query_playbook.yml
      vars:  
        query: "select alertType,tempId from template_details where ticketType='{{ ticketType }}' ;"

    - name: Loop through json_data.body and check for 'alert' key in short_desc and desc
      debug:
        msg: " {{ item | json_query('[*].shortDescription') }} and  {{ item | json_query('[*].fullDescription') }} "
        #var: "{{ item.shortDescription }}"
      loop: "{{ json_data.body }}"
      loop_control:
        loop_var: item
      #register: item.shortDescription
      when: "'alert_result.results[0].rows[0].alertType' in item.shortDescription and 'alert_result.results[0].rows[0].alertType' in item.fullDescription"


    -
    - name: Display Cred Details Result
      debug:
        var: alert_result.results[0].rows[0].alertType
