---
- name: Fetch Incident and Update Incident fields data from ServiceNow
  hosts: localhost
  gather_facts: no
  vars:
    short_Descriptions: "{{ short_Descriptions }}"
    mysql_query: "SELECT * FROM incidentdata.incidentConfigDetails;;"
  tasks:
    - block:
        - name: include  playbook to fetch Incident
          include: includeDbconnectTofetchINC.yml 
          register: short_Descriptions
        - name: print var
          debug:
            var: short_Descriptions

        - name: Call the MySQL Query Playbook
          include_tasks: mysql_query_playbook.yml
          vars:
            query: "{{ mysql_query }}"

        - name: Display the result from the MySQL Query Playbook
          debug:
           var: query_result

        - name: Display the result from the MySQL Query Playbook
          debug:
           var: query_result.ci_name 
     
        - name: Separating ciname
          set_fact:
            ciname_value: "{{ short_Descriptions  | regex_search('query_result.ci_name is (' + query_result.ci_name + ')', '\\1') }}"
            
        - name: Display the ci_name
          debug:
           var: ciname_value
        - name: Extract ci_name using json_query 
          set_fact: 
           extracted_ci_name: "{{ json_data.query_result.query_result[0].ci_name }}"
        - name: ci_name value 
          debug:
           var: extracted_ci_name

      
      rescue:
        - name: Log Output For Failure
          debug:
            msg: "Log : FAILED : Task {{ ansible_failed_task.name }} Failed and the ERROR:
              {{ ansible_failed_result }}"
          failed_when: true

